name: TEST REPO
on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
      
    - name: Run EC Validator
      uses: ./
      with:
        image: "quay.io/redhat-appstudio/ec-golden-image:latest"
        key: ${{ vars.PUBKEY }}
        policy: "github.com/enterprise-contract/config//minimal"
